### ISSUE TITLE
Search does not work for model relations

### ISSUE THREAD

**Issue by amanbop** [jbox-web/ajax-datatables-rails#29]
1. This only works efficiently for a flat one model rendering. e.g. Client.all
2. This does not work for anything more complicated where you have model relations using has_many and belongs_to involved and you want to search or sort on child table.

e.g. the follow scenario does not work
class Client < ActiveRecord::Base
has_many :orders
has_many :addresses
end

You want to show the following view

Client            Address                    Orders
ABC               Street1                     3
                       Street2
1. There is no easy way to form the query without using :include or :join
2. Even if you use :include, searching on Address does not work.
3. Order on Orders does not work.

Is there any plan to make it more useful by adding support for these scenarios?

**Comment by antillas21** [comment]
Hi @amanbop ,

I'm trying to wrap my head around what is it you mean when you say that this gem only works for a flat one model rendering like `Client.all`, and that it doesn't work with more complicated model relationships like a `has_many/belongs_to` scenario.

The first version of this gem used to work like what you point out. But it was re-worked since version 0.1.0 to give room for the developer to write _just the right ActiveRecord/Arel/SQL query_ needed to get the job done.

Now, I don't understand the example you have written in your comment, as formatting was lost due to markdown, could you provide an example formatted as a table that we could work with in order for me to help you troubleshoot?

Github comments use markdown, so you can use the `|` (pipe) character to separate columns, like this:

```
| Client | Address | Orders |
----------|-----------|-----------|
| John Doe | 123 Some St. | #123, #124 |
| Jane Doe | 234 Main St. | #789 | #9078 |
```

Translates to

| Client | Address | Orders |
| --- | --- | --- |
| John Doe | 123 Some St. | #123, #124 |
| Jane Doe | 234 Main St. | #789 |

**Comment by donovan-duplessis** [comment]
Hey @antillas21 ,

If I understand point number 3 by @amanbop correctly, currently the gem cannot order by a has_many (group-concat) field.

Essentially, even if you create a virtual model field in `client.rb`, say for example:

``` ruby
def order_numbers
  orders.map(&:number).join(', ')
end
```

For the above to work, you would need to add `order_numbers` to the `@sortable_columns` array.  The following example query could be used:

``` ruby
Client.joins(:orders).group('clients.id').all
```

The datatable will load correctly with this dataset but as soon as you order by the "Orders" field, it will break, because the implementation will add ``ORDER BY comments_list` to the query.

I have solved this issue in my fork.  It is a useful feature to have; maybe we can discuss this over email?

Regards,
Donovan

**Comment by antillas21** [comment]
Hey @donovan-duplessis ,

I'm up for suggestions and contributions, so feel free to comment here in this thread or [email me](mailto:antillas21@gmail.com) and start a conversation on extending this gem features.

Looking forward to your comments :smile:

**Comment by donovan-duplessis** [comment]
Hey @antillas21,

I made this change to the search_condition function:

``` ruby
model, column = column.split('.')
unless column.nil?
  model = model.singularize.titleize.gsub( / /, '' ).constantize
  model.arel_table[column.to_sym].matches("%#{value}%")
end
```

Now you can order across the group_concat, with this example:

``` ruby
@sortable_columns ||= ['clients.name', 'order_numbers']

records.map do |record|
  [
    record.name,
    record.order_numbers
  ]
end
```

Here is a query example based on his issue:

``` ruby
def get_raw_records
  Client.joins(:orders).select('clients.id, clients.name, group_concat(orders.number) as order_numbers').group('clients.id')
end
```

One thing to note, it is very difficult to search across a group_concat properly.  In MySQL you can, by appending this to the end of your query for example:

``` sql
HAVING order_numbers like '%number%'
```

So I don't enable sorting on these has_many columns on the datagrid itself, eg (in aoColumns):

Add `{bSortable : false}` to order_numbers column definition

I normally display the has_many column in the datagrid as a popover/tooltip etc.

Regards,
Donovan

**Comment by amanbop** [comment]
@antillas21 : Thanks for your response. Here is my code :

++++++++++++++++++++++++++++++++
class Client < ActiveRecord::Base
  has_many :orders
  has_many :addresses
end

class Order < ActiveRecord::Base
  belongs_to :client
end

class Address < ActiveRecord::Base
  belongs_to :client
end
+++++++++++++++++++++++++++++++

clients.js.cofee

jQuery ->
  $('#clients').dataTable
    paginationType: "full_numbers"
    processing: true
    serverSide: true
    ajax: $('#clients').data('source')

+++++++++++++++++++++++++++++++++

class ClientsController < ApplicationController

  def index
    respond_to do |format|
      format.html
      format.json { render json: ClientDatatable.new(view_context) }
    end
  end
end

+++++++++++++++++++++++++++++++
views/clients/index.html.erb

<%- model_class = Client -%>

<div class="page-header">
  <%=t '.title', :default => model_class.model_name.human.pluralize.titleize %>
</div>

<table id="clients" class="table table-striped display", data-source="<%= clients_path(format: :json) %>" >
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Orders Count</th>
    </tr>
  </thead>
  <tbody>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_client_path,
            :class => 'btn btn-primary' %>
<%= link_to 'Client', clients_path %>

+++++++++++++++++++++++++++++++++

class ClientDatatable < AjaxDatatablesRails::Base
  # uncomment the appropriate paginator module,
  # depending on gems available in your project.
  # include AjaxDatatablesRails::Extensions::Kaminari
   include AjaxDatatablesRails::Extensions::WillPaginate
  # include AjaxDatatablesRails::Extensions::SimplePaginator

  def_delegator :@view, :link_to
  def_delegator :@view, :h
  def_delegator :@view, :mail_to
  def_delegator :@view, :edit_resource_path

  def sortable_columns
    # list columns inside the Array in string dot notation.
    # Example: 'users.email'
    @sortable_columns ||= ["clients.name"]
  end

  def searchable_columns
    # list columns inside the Array in string dot notation.
    # Example: 'users.email'
    @searchable_columns ||= ["clients.name"]
  end

  private

  def data
    records.map do |record|
      [
        # comma separated list of the values for each cell of a table row
        # example: record.attribute,
       link_to(record.name, record),
       record.addresses.map {|address|  link_to(address.name,address)},
       record.orders.count
     ]
    end
  end

  def get_raw_records
    # insert query here
    Client.all
  end

  # ==== Insert 'presenter'-like methods below if necessary
end
++++++++++++++++++++++++
Here is the output I want to see is (where Order Count is per Client) :

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Orders Count</th>
    </tr>
  </thead>
  <tbody>
  <tr>
  <td rowspan=2>Abc</td>
  <td>Stree1</td>
  <td rowspan=2>3</td>
  </tr>
  <tr>
 
  <td>Stree2</td>
  
  </tr>  
  </tbody>
</table>

and
1. I want to sort on Name,Address and Orders Count columns
2. I want to search on Name and Address columns
3. I do not want to write raw sql or explicit join conditions, even though I can without any problem

Now:
1. Sorting on Name only and searching on Name only works 
2. Sorting on Address and Count does not work
3. Searching on Address does not work

So to make it work I experimented whole day yesterday trying to use params[:order]["0"][:column] value and provide different SQLs and data blocks in ClientDatatale as below, which is not elegant at all. However I ran into issues here also as referring to params before data block produces unknown method error and     if params[:order]['0'][:column] == "0"    statement just dies silently. Please suggest how best I can use this gem to solve my problem.

  def sortable_columns
    # list columns inside the Array in string dot notation.
    # Example: 'users.email'
      if params[:order]['0'][:column] == "0"
        @sortable_columns = ["clients.name"]
      elsif params[:order]['0'][:column] == "1"
        @sortable_columns = ["addresses.name"]
      end
  end

  def searchable_columns
    # list columns inside the Array in string dot notation.
    # Example: 'users.email'
     if params[:order]["0"][:column] == "0"
        @searchable_columns ||= ["clients.name"]
     elsif params[:order]["0"][:column] == "1"
       @searchable_columns ||= ["addresses.name"]
      end
  end

  private

  def data

```
if params[:order]["0"][:column] == "0"
records.map do |record|
  [  
   link_to(record.name, record),
   record.addresses.map {|address|  link_to(address.name,address)},
   record.orders.count       
  ]
end
elsif params[:order]["0"][:column] == "1"
records.map do |record|
  [
   link_to(record.client.name, record.client),
   link_to(address.name,address),
   record.client.orders.count   
  ]
end
end
```

  end

  def get_raw_records
    # insert query here
    if params[:order]["0"][:column] == "0"
      Client.all
    elsif params[:order]["0"][:column] == "1"
     Address.all
    end

**Comment by antillas21** [comment]
@donovan-duplessis ooh, I see.

Could composing the `search_condition` method like this help in any way? (I know, testing will be required).

``` ruby
def search_condition(column, value)
  model, column = column.split('.')
  model = model.singularize.titleize.gsub( / /, '' ).constantize
  return if column.nil?

  searchable = model.arel_table[column.to_sym]
  searchable.matches("%#{value}%").or(having(searchable).matches("%#{value}%"))
end
```

Could you test in your scenario? I think with Arel, this would perform a HAVING clause on the column with a LIKE or ILIKE condition, like your MySQL example of:

``` sql
HAVING order_numbers like '%number%'
```

**Comment by antillas21** [comment]
@amanbop 

I need time to fully understand your example. But after a first pass I can see that, this relates to the case described by @donovan-duplessis . But I also see the following:
- You are trying to nest N rows inside a single dataTable row for the Addresses column. I would recommend to check jQuery.dataTables documentation first to see if this is a feature of the plugin.
- On the Orders Count column, I would recommend the simplest solution, an `orders_count` counter cache column on the `Client` model table which would be updated every time a new order is created/deleted for that customer and thus, saving SQL calculations while building this. :smile: `ActiveRecord` can easily take care of this for you.
- To save effort while declaring delegators to your `ClientDatatable` class, I would recommend you [take a look here](https://github.com/antillas21/ajax-datatables-rails#using-view-helpers).

**Comment by amanbop** [comment]
@antillas21 
Thanks for the reply. Since my case is complicated, best way for me is to build separate queries based on the sorting and searching column. For that I need to be able to access params hash effectively. Currently it is only accessible from inside data or get_raw_records methods and not outside it. What would be the reason for that?

**Comment by antillas21** [comment]
@amanbop 

That's not accurate. We defined a delegator to the params hash in the base class, here: https://github.com/antillas21/ajax-datatables-rails/blob/master/lib/ajax-datatables-rails/base.rb#L7

This means, you should be able to use the params hash as it were inside a controller. Take a look at these examples inside the gem itself:
- https://github.com/antillas21/ajax-datatables-rails/blob/master/lib/ajax-datatables-rails/base.rb#L38
- https://github.com/antillas21/ajax-datatables-rails/blob/master/lib/ajax-datatables-rails/base.rb#L77-L78
- https://github.com/antillas21/ajax-datatables-rails/blob/master/lib/ajax-datatables-rails/base.rb#L101
- https://github.com/antillas21/ajax-datatables-rails/blob/master/lib/ajax-datatables-rails/base.rb#L111-L126

As you can see, inside your class, you are free to use the params hash wherever needed.

**Comment by amanbop** [comment]
@antillas21: 
I got the params working. I think the issue was my gem code was old. I worked after update. So I got the datatables working but the issue of sorting on Order column remains unresolved. 

@donovan-duplessis 
I tried your idea but I am seeing issues with SQL query being generated in my system. e.g. say 

model Post has_many comments

so this query works nicely on console.
Post.joins(:comments).select("posts.id,posts.title,group_concat(comments.title) as comments_titles").group("posts.id")
it generates this SQL:
 SELECT posts.id,posts.title,group_concat(comments.title) as comments_titles FROM "posts" INNER JOIN "comments" ON "comments"."post_id" = "posts"."id" GROUP BY posts.id

However the same query in the get_raw_records method generates following sql and errors out:
SELECT COUNT(posts.title,group_concat(comments.title) as comments_titles) AS count_posts_title_group_concat_comments_title_as_comments_titles, posts.id AS posts_id FROM "posts" INNER JOIN "comments" ON "comments"."post_id" = "posts"."id" GROUP BY posts.id

SQLite3::SQLException: near "as": syntax error: SELECT COUNT(posts.title,group_concat(comments.title) as comments_titles) AS count_posts_title_group_concat_comments_title_as_comments_titles, posts.id AS posts_id FROM "posts" INNER JOIN "comments" ON "comments"."post_id" = "posts"."id" GROUP BY posts.id
Completed 500 Internal Server Error in 28ms

You see it is adding and extra COUNT( around the whole set. Have you seen this before? Any idea how to make this work?

**Comment by antillas21** [comment]
@amanbop LOL, so we've been referring to different versions of the gem all this time?

Good to know you are on the latest release now :smile: 

About that extra count, it's because we need to retrieve two record totals: one for the grand total of records existing and retrieved by the query declared in the `get_raw_records` method, and one for the filtered set of records after entering any value in the search field(s). [Please take a look here](https://github.com/antillas21/ajax-datatables-rails/blob/master/lib/ajax-datatables-rails/base.rb#L36-L42) to see where are these `count` calls inserted.

Now, today may be your lucky day, as @mitchej123 has contributed a pull request to fix an issue presenting with queries such as the one you specify `select("table_name.field, table_name.other_field, and more complex selections")` and the result of calling `count` on it when working with ActiveRecord 4.1.x

[Please refer to this commit](https://github.com/antillas21/ajax-datatables-rails/commit/c9d040a9b5d59cae93c62a059b7fa61f308686c1) to see the fix for this.

Currently, this fix is unreleased, but it is available in the master branch of this repo. So you may update your Gemfile like this:

``` ruby
gem 'ajax-datatables-rails', git: 'git@github.com:antillas21/ajax-datatables-rails.git', branch: 'master'
```

or you can declare a private method in your `ClientDatatable` class like so:

``` ruby
def as_json(options = {})
  {
    :draw => params[:draw].to_i,
    :recordsTotal =>  get_raw_records.count(:all),
    :recordsFiltered => filter_records(get_raw_records).count(:all),
    :data => data
  }
end
```

Hope any of this is of help to you.

**Comment by amanbop** [comment]
@antillas21 
Your new as_jason method works. However the new seach_condition dies with following error:

```
 NoMethodError (undefined method `having' for #<PostDatatable:0x9b08a48>):
```

Am I doing something wrong?

```
def search_condition(column, value)
  model, column = column.split('.')
  model = model.singularize.titleize.gsub( / /, '' ).constantize
  return if column.nil?

  searchable = model.arel_table[column.to_sym]
  searchable.matches("%#{value}%").or(having(searchable).matches("%#{value}%"))
end
```

**Comment by antillas21** [comment]
@amanbop 

Yeah, I suspected that, it's experimental code and completely untested, though it's just an idea of how to construct the query... looking at some Arel examples, I see that the `having` method has to be called on an `Arel::Table` object, so this could work:

``` ruby
def search_condition(column, value)
  model, column = column.split('.')
  model = model.singularize.titleize.gsub(/ /, '').constantize
  return if column.nil?

  table = model.arel_table
  searchable_column = table[column.to_sym]

  like_search = searchable_column.matches("%#{value}%")
  having_search = table.having(searchable_column).matches("%#{value}%")

  like_search.or(having_search)
end
```

**disclaimer:** this is a top-of-my-head idea, I need to do some research on how to solve this via Arel to grant developers flexibility.

As always, you can and are welcome override this method in your own datatable class to find just the right trick that fits the bill ; )

**Comment by amanbop** [comment]
@antillas21 
Tried your code. Erros says:

```
NoMethodError (undefined method `matches' for #<Arel::SelectManager:0xbc5e3dc>)
```

Then experimented with arel and changed 

```
having_search = table.having(searchable_column).matches("%#{value}%")
```

to

```
having_search = table.having(searchable_column.matches("%#{value}%"))
```

i.e. moved a closing brace to the end. The error changed to 

```
TypeError (Cannot visit Arel::SelectManager):
```

**Comment by antillas21** [comment]
Mmhh... take a look at this (from a sample project)

``` ruby
table = Client.arel_table
# => #<Arel::Table:0x007fad1448e900 @name="clients", @engine=Client(id: integer, name: string, email: string, created_at: datetime, updated_at: datetime), @columns=nil, @aliases=[], @table_alias=nil, @primary_key=nil> 

searchable_column = table[:name]
 #=> #<struct Arel::Attributes::Attribute relation=#<Arel::Table:0x007fad1448e900 @name="clients", @engine=Client(id: integer, name: string, email: string, created_at: datetime, updated_at: datetime), @columns=nil, @aliases=[], @table_alias=nil, @primary_key=nil>, name=:name> 

like_search = searchable_column.matches("%Ana%")
# => #<Arel::Nodes::Matches:0x007fad146360f0 @left=#<struct Arel::Attributes::Attribute relation=#<Arel::Table:0x007fad1448e900 @name="clients", @engine=Client(id: integer, name: string, email: string, created_at: datetime, updated_at: datetime), @columns=nil, @aliases=[], @table_alias=nil, @primary_key=nil>, name=:name>, @right="%Ana%">

like_search.to_sql
# => "`clients`.`name` LIKE '%Ana%'" 
# this is the default query as of right now

having_search = table.having(searchable_column.matches("%Ana%"))
# => #<Arel::SelectManager:0x007fad1467ced8 @engine=Client(id: integer, name: string, email: string, created_at: datetime, updated_at: datetime), @ctx=#<Arel::Nodes::SelectCore:0x007fad1467ce38 @source=#<Arel::Nodes::JoinSource:0x007fad1467ce10 @left=#<Arel::Table:0x007fad1448e900 @name="clients", @engine=Client(id: integer, name: string, email: string, created_at: datetime, updated_at: datetime), @columns=nil, @aliases=[], @table_alias=nil, @primary_key=nil>, @right=[]>, @top=nil, @set_quantifier=nil, @projections=[], @wheres=[], @groups=[], @having=#<Arel::Nodes::Having:0x007fad1467caa0 @expr=#<Arel::Nodes::Matches:0x007fad1467cf28 @left=#<struct Arel::Attributes::Attribute relation=#<Arel::Table:0x007fad1448e900 @name="clients", @engine=Client(id: integer, name: string, email: string, created_at: datetime, updated_at: datetime), @columns=nil, @aliases=[], @table_alias=nil, @primary_key=nil>, name=:name>, @right="%Ana%">>, @windows=[]>, @bind_values=[], @ast=#<Arel::Nodes::SelectStatement:0x007fad1467ce60 @cores=[#<Arel::Nodes::SelectCore:0x007fad1467ce38 @source=#<Arel::Nodes::JoinSource:0x007fad1467ce10 @left=#<Arel::Table:0x007fad1448e900 @name="clients", @engine=Client(id: integer, name: string, email: string, created_at: datetime, updated_at: datetime), @columns=nil, @aliases=[], @table_alias=nil, @primary_key=nil>, @right=[]>, @top=nil, @set_quantifier=nil, @projections=[], @wheres=[], @groups=[], @having=#<Arel::Nodes::Having:0x007fad1467caa0 @expr=#<Arel::Nodes::Matches:0x007fad1467cf28 @left=#<struct Arel::Attributes::Attribute relation=#<Arel::Table:0x007fad1448e900 @name="clients", @engine=Client(id: integer, name: string, email: string, created_at: datetime, updated_at: datetime), @columns=nil, @aliases=[], @table_alias=nil, @primary_key=nil>, name=:name>, @right="%Ana%">>, @windows=[]>], @orders=[], @limit=nil, @lock=nil, @offset=nil, @with=nil>> 

having_search.to_sql
# => "SELECT FROM `clients`  HAVING `clients`.`name` LIKE '%Ana%'" 
# this is the missing piece you might need

 like_search.or(having_search).to_sql
# => "(`clients`.`name` LIKE '%Ana%' OR (SELECT FROM `clients`  HAVING `clients`.`name` LIKE '%Ana%'))" 
# I'm not so sure about how this is joined :\
```

If I do this:

``` ruby
having_search = table.having(searchable_column.matches("%Ana%")).project(Arel.star)
# => #<Arel::SelectManager:0x007fad1479f4c8 @engine=Client(id: integer, name: string, email: string, created_at: datetime, updated_at: datetime), @ctx=#<Arel::Nodes::SelectCore:0x007fad1479f450 @source=#<Arel::Nodes::JoinSource:0x007fad1479f428 @left=#<Arel::Table:0x007fad1448e900 @name="clients", @engine=Client(id: integer, name: string, email: string, created_at: datetime, updated_at: datetime), @columns=nil, @aliases=[], @table_alias=nil, @primary_key=nil>, @right=[]>, @top=nil, @set_quantifier=nil, @projections=["*"], @wheres=[], @groups=[], @having=#<Arel::Nodes::Having:0x007fad1479f270 @expr=#<Arel::Nodes::Matches:0x007fad1479f4f0 @left=#<struct Arel::Attributes::Attribute relation=#<Arel::Table:0x007fad1448e900 @name="clients", @engine=Client(id: integer, name: string, email: string, created_at: datetime, updated_at: datetime), @columns=nil, @aliases=[], @table_alias=nil, @primary_key=nil>, name=:name>, @right="%Ana%">>, @windows=[]>, @bind_values=[], @ast=#<Arel::Nodes::SelectStatement:0x007fad1479f478 @cores=[#<Arel::Nodes::SelectCore:0x007fad1479f450 @source=#<Arel::Nodes::JoinSource:0x007fad1479f428 @left=#<Arel::Table:0x007fad1448e900 @name="clients", @engine=Client(id: integer, name: string, email: string, created_at: datetime, updated_at: datetime), @columns=nil, @aliases=[], @table_alias=nil, @primary_key=nil>, @right=[]>, @top=nil, @set_quantifier=nil, @projections=["*"], @wheres=[], @groups=[], @having=#<Arel::Nodes::Having:0x007fad1479f270 @expr=#<Arel::Nodes::Matches:0x007fad1479f4f0 @left=#<struct Arel::Attributes::Attribute relation=#<Arel::Table:0x007fad1448e900 @name="clients", @engine=Client(id: integer, name: string, email: string, created_at: datetime, updated_at: datetime), @columns=nil, @aliases=[], @table_alias=nil, @primary_key=nil>, name=:name>, @right="%Ana%">>, @windows=[]>], @orders=[], @limit=nil, @lock=nil, @offset=nil, @with=nil>> 

having_search.to_sql
# => "SELECT * FROM `clients`  HAVING `clients`.`name` LIKE '%Ana%'" 

like_search.or(having_search).to_sql
# => "(`clients`.`name` LIKE '%Ana%' OR (SELECT * FROM `clients`  HAVING `clients`.`name` LIKE '%Ana%'))" 
# still not sure, but at least it includes something to select from the table (*)
```

**Comment by amanbop** [comment]
@antillas21 
While using your new method as_json to override the original method works, but the pagination info does not come out correct. It says:

Showing 0 to 0 of 0 entries (filtered from NaN total entries)
How to fix this?

**Comment by antillas21** [comment]
@amanbop 

Funny thing is... you would need to check what method to pass to the `as_json` method when it comes to the `:recordsTotal and :recordsFiltered` keys.

**Comment by amanbop** [comment]
@antillas21 
I got :recordsTotal to work by modifying the to_json method like :

```
@query_has_group_by = false

  def as_json(options = {})
    {
      :draw => params[:draw].to_i,
      :recordsTotal => (@query_has_group_by) ? (get_raw_records.count(:all).length) : (get_raw_records.count(:all)),
      :recordsFiltered => (@query_has_group_by) ? ((filter_records(get_raw_records).count(:all)).length) : (filter_records(get_raw_records).count(:all)),
      :data => data
    }
  end

  def get_raw_records

    @query_has_group_by = true
     Client.joins(:custodians).select("clients.id,clients.name,group_concat(custodians.last_name) as custodians_last_name_concat,count(custodians.id) as custodians_count").group("clients.id")

    end
  end


```

how ever the filtered records is still messed up showing:

(filtered from NaN total entries)

**Comment by travisdavis75** [comment]
Does anyone have a fix for the total value of NaN?

**Comment by ajahongir** [comment]
https://github.com/antillas21/ajax-datatables-rails/issues/159#issuecomment-229452252

**Comment by n-rodriguez** [comment]
https://github.com/jbox-web/ajax-datatables-rails/issues/159#issuecomment-301194631
